name: test workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello team
        run: echo "Welcome to CloudEQS"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye team
        run: echo "Bye! Thanks"
        shell: bash
