name: Manual Python and PowerShell Workflows
#env:
#  NAME: 'Snyk Demo'

on:
  workflow_dispatch:
    inputs:
      Tag:
        description: The git tag name to pass to the Python and PowerShell scripts.
        required: true
        type: string
env:
  COMMIT_ID: ${{ github.sha }}
  svc_matillion_username: 'bikram_test@gmail.com'
  svc_matillion_password: 'test1234'
  Matillion_Project: 'CLOUDX_DEMO'
  Matillion_Group: 'TEST'
  Matillion_Version: 'v1.1'
  Matillion_Instance: '192.168.1.1'
  svc_repos_email: 'test@gmail.com'
  svc_repos_password: 'test1234'
  
  
jobs:
  get_commit_id:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: GetCommitId
        run: |
          pwsh -File ./.github/workflows/getcommitid.ps1 -SourceTag ${{ inputs.Tag }}
        #echo "COMMIT_ID=$commitid" >> $GITHUB_ENV
        shell: pwsh
     
      - name: print commit id  
        #run: echo "COMMIT ID IS ${{env.COMMIT_ID}}"
        #run: echo "COMMIT ID IS ${{ steps.generate_commit_id.outputs.COMMIT_ID }}"
        run: echo "COMMIT ID IS ${{ env.COMMIT_ID }}"

    #  - name: my variable
     #   run: echo "Hello $NAME"
        


  python:
    runs-on: ubuntu-latest
    needs: get_commit_id
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python ./.github/workflows/matillion_api_call.py ${{env.svc_matillion_username}} ${{env.svc_matillion_password}} ${{env.Matillion_Project}} ${{env.Matillion_Group}} ${{env.Matillion_Version}} ${{env.Matillion_Instance}} ${{env.svc_repos_email}} ${{env.svc_repos_password}} ${{ env.COMMIT_ID }}
        
